### ISSUE TITLE
the code is empty ?

### ISSUE THREAD

**Issue by XiaoqingNLP** [zdou0830/DAFE#1]

**Comment by alphadl** [comment]
+1

**Comment by zdou0830** [comment]
Thanks for your interest! The code will be available by the end of the year hopefully. Sorry about the delay.

**Comment by jind11** [comment]
+1

**Comment by zdou0830** [comment]
> +1

Hi, thanks for your interest! You may find the uncleaned code in the branch "ugly". I will upload the cleaned version soon.

**Comment by jind11** [comment]
Thank you so much! Look forward to the cleaned version!

**Comment by jind11** [comment]
Hi, could you also post the link for the data downloading? I found it not trivial to find all of them. Thanks!

**Comment by zdou0830** [comment]
> Hi, could you also post the link for the data downloading? I found it not trivial to find all of them. Thanks!

Here is the link for the OPUS data: https://github.com/khayrallah/domain-adaptation-data.

**Comment by zdou0830** [comment]
The cleaned code is uploaded. Detailed instructions will be available later. Thanks!
